services:
  # Infrastructure Services
  postgres:
    image: postgres:15-alpine
    container_name: ododocs-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${HOME}/volumes/ododocs/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - ododocs-infra-network

  redis:
    image: redis:alpine
    container_name: ododocs-redis
    restart: always
    volumes:
      - ${HOME}/volumes/ododocs/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - ododocs-infra-network



networks:
  ododocs-infra-network:
    name: ododocs-infra-network
    driver: bridge
